[unstable]
# allow us to build core for our specific target
build-std = ["core", "compiler_builtins"]

[build]
target = "x86_64-rOSt.json"

[target.'cfg(target_os = "none")']
runner = "bootimage runner"